/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const SESSIONS = ["London", "New York", "Asia", "London/NY Overlap"];
export const SYMBOLS = ["NQ", "ES", "Gold", "Other"];
export const ACCOUNTS = ["Live", "Funded", "Paper", "Demo"];
export const PNL_RATES: Record<string, number> = { NQ: 2, ES: 5, Gold: 10, Other: 1 };
export const ENTRY_WINDOWS = ["1m", "5m", "15m", "1H", "4H", "Daily"];
export const MENTAL_STATES = [
  "Focused", "Calm", "Patient", "Disciplined", "Confident", "In The Zone",
  "Tired", "Fatigued", "Stressed", "Anxious", "Overconfident", "Fearful",
  "Hesitant", "Frustrated", "Impatient", "Undisciplined", "Revenge", "FOMO",
  "Bored", "Distracted", "Euphoric", "Numb", "Other"
];
export const RULES = [
  "Waited for confirmation", "Respected stop loss", "Proper position sizing",
  "Traded in kill zone", "Followed session plan", "No revenge trading",
  "Respected daily loss limit", "Took partials at TP1"
];
export const MISTAKE_CATS = [
  "Entered too early", "Entered too late", "Moved stop loss", "Overtraded",
  "Ignored invalidation", "Sized too large", "Revenge traded", "Chased entry",
  "FOMO trade", "Skipped valid setup", "Exited too early", "Held too long", "Other"
];
export const PREMARKET_ITEMS = [
  "Checked economic calendar", "Identified key levels", "Set daily loss limit",
  "Defined session bias", "Reviewed yesterday's trades", "Set max trades for session",
  "No major news risk", "Reviewed playbook setups"
];
export const BIAS_OPTS = ["Bullish", "Bearish", "Neutral", "No Bias"];
export const WDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const QUOTES = [
  { q: "The goal of a successful trader is to make the best trades. Money is secondary.", a: "Alexander Elder" },
  { q: "Cut losses short. Let profits run.", a: "Jesse Livermore" },
  { q: "The market is a device for transferring money from the impatient to the patient.", a: "Warren Buffett" },
  { q: "Plan the trade and trade the plan.", a: "Trading Principle" },
  { q: "In trading, the person who makes the fewest mistakes wins.", a: "Trading Principle" },
  { q: "Don't focus on making money; focus on protecting what you have.", a: "Paul Tudor Jones" },
  { q: "The trend is your friend until the end when it bends.", a: "Ed Seykota" },
  { q: "Do more of what works and less of what doesn't.", a: "Steve Clark" },
  { q: "Trade what you see, not what you think.", a: "Trading Principle" },
  { q: "Process over outcome. Always.", a: "Trading Principle" },
  { q: "Amateurs want to be right. Professionals want to make money.", a: "Trading Principle" },
  { q: "Risk management is the difference between trading and gambling.", a: "Trading Principle" },
  { q: "The best trades are the ones you almost didn't take.", a: "Trading Principle" },
  { q: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn" },
  { q: "The four most dangerous words: this time it's different.", a: "Sir John Templeton" },
  { q: "Confidence is not 'I will profit.' It is 'I will be fine if I don't.'", a: "Yvan Byeajee" },
  { q: "Your system doesn't need to be perfect. It just needs an edge.", a: "Trading Principle" },
  { q: "Accepting losses is the most important investment device.", a: "Gerald Loeb" },
  { q: "Know your edge, trade your edge, protect your edge.", a: "Trading Principle" },
  { q: "Patience is not waiting—it's keeping a good attitude while waiting.", a: "Joyce Meyer" },
];

export const DEFAULT_TRADES = [
  {
    id: "t1",
    date: "2026-04-07",
    timeEntry: "09:55",
    timeClose: "09:59",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB B&R (Continuation) Model",
    entryWindow: "15m",
    entry: 24188.75,
    sl: 24240,
    tp: 24069.75,
    exit: 24069.75,
    pnl: 238,
    rr: 2.32,
    lots: 1,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Traded in kill zone"],
    mentalPre: "Focused",
    mentalDuring: "Calm",
    mentalPost: "Satisfied",
    notes: "No partials since I only traded 1 micro.",
    tags: ["ORB", "Continuation"],
    images: [],
    urls: []
  },
  {
    id: "t2",
    date: "2026-04-09",
    timeEntry: "09:49",
    timeClose: "09:53",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB Reversal Model",
    entryWindow: "5m",
    entry: 25081.25,
    sl: 25109,
    tp: 25019,
    exit: 25019,
    pnl: 249,
    rr: 2.24,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Proper position sizing"],
    mentalPre: "Calm",
    mentalDuring: "Disciplined",
    mentalPost: "Balanced",
    notes: "After failing to continue higher during the first 15 minutes, price action retraced back inside the range. Once we closed back inside, I noticed, through the footprint, that buyers were trapped at the highs. We also closed below both the NY Open and a footprint imbalance, so I placed a limit order at the NY Open (FVG). My target was the ORB Low for a quick 1:2 risk-to-reward...",
    tags: ["ORB", "Reversal", "Footprint"],
    images: [],
    urls: []
  },
  {
    id: "t3",
    date: "2026-04-13",
    timeEntry: "09:55",
    timeClose: "10:14",
    symbol: "NQ",
    direction: "Long",
    session: "New York",
    strategy: "15m ORB B&R (Continuation) Model",
    entryWindow: "15m",
    entry: 25270.75,
    sl: 25226.75,
    tp: 25350.75,
    exit: 25270.75,
    pnl: 0,
    rr: 0,
    lots: 1,
    account: "Paper",
    followedRules: ["Respected stop loss"],
    mentalPre: "FOMO",
    mentalDuring: "Anxious",
    mentalPost: "Relieved",
    notes: "I dont like how I traded todayè; I had a meeting at 10am so I wasnt supposed to be on the chart for the session because I knew I wouldnt focus. Also since i dont have real time data i trade 10m late and I was on Youtube listening to live trade From Alex so I was spoiled; thats why i put the trade at BE cuz i wasnt supposed to take it, but was from the setup. I would have played, but wouldnt be A+ since no confluence from the footprint. Good confluence tho from th eoverlapping PDL, PD VAL and PW POC.",
    tags: ["BE", "FOMO"],
    images: [],
    urls: []
  },
  {
    id: "t4",
    date: "2026-04-15",
    timeEntry: "10:01",
    timeClose: "10:28",
    symbol: "NQ",
    direction: "Long",
    session: "New York",
    strategy: "15m ORB B&R (Continuation) Model",
    entryWindow: "15m",
    entry: 26059.5,
    sl: 26022.75,
    tp: 26133,
    exit: 26133,
    pnl: 294,
    rr: 2,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Proper position sizing", "Traded in kill zone"],
    mentalPre: "Calm",
    mentalDuring: "Patient",
    mentalPost: "Confident",
    notes: "PA was bad the first 30m: with lot of fake outs. I was really patient for my setups. I was ready to go BE if the trades was not going my way i.e reverse ORB or ES reverse the NY Open (lot of divergence). I was confident once we started to based above at 10:10AM. BE at 10:15AM after the BOS and ES based above the ORB High.",
    tags: ["ORB", "Patience"],
    images: [],
    urls: []
  },
  {
    id: "t5",
    date: "2026-04-16",
    timeEntry: "10:17",
    timeClose: "10:35",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB B&R (Continuation) Model",
    entryWindow: "5m",
    entry: 26345,
    sl: 26387,
    tp: 26258,
    exit: 26387,
    pnl: -168,
    rr: -1,
    lots: 2,
    account: "Paper",
    followedRules: ["Respected stop loss", "Proper position sizing"],
    mentalPre: "In The Zone",
    mentalDuring: "Focused",
    mentalPost: "Accepting",
    notes: "Clear divergence developed between the two assets. After NQ took the ATH, I expected a pullback and was already short‑biased. Once a strong short setup formed, I noticed ES showing significantly more weakness than NQ — confirming the divergence. I took the short at the ORB Low + PDH...",
    tags: ["Loss", "Divergence"],
    images: [],
    urls: []
  },
  {
    id: "t6",
    date: "2026-04-16",
    timeEntry: "10:55",
    timeClose: "11:10",
    symbol: "NQ",
    direction: "Long",
    session: "New York",
    strategy: "Previous Day Reversal Model",
    entryWindow: "15m",
    entry: 26412,
    sl: 26377.25,
    tp: 26481.5,
    exit: 26481.5,
    pnl: 278,
    rr: 2,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Proper position sizing", "Traded in kill zone"],
    mentalPre: "In The Zone",
    mentalDuring: "Disciplined",
    mentalPost: "Excited",
    notes: "Market structure was clearly bullish, with no indication that sellers wanted to push price lower. After we retested the ATH + PDH and buyers held the level, I shifted my bias to long. I entered on the retest once it was clear that sellers were stuck and unable to push price back inside. Strong trade — clean read, clean execution.",
    tags: ["Winner", "Reversal", "Bullish"],
    images: [],
    urls: []
  },
  {
    id: "t7",
    date: "2026-04-17",
    timeEntry: "09:53",
    timeClose: "09:57",
    symbol: "NQ",
    direction: "Long",
    session: "New York",
    strategy: "15m ORB Reversal Model",
    entryWindow: "5m",
    entry: 26754.5,
    sl: 26729.25,
    tp: 26805.25,
    exit: 26805.25,
    pnl: 203,
    rr: 2.01,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Traded in kill zone"],
    mentalPre: "Distracted",
    mentalDuring: "Calm",
    mentalPost: "Balanced",
    notes: "Was initially looking for a B&R, but once it became clear buyers were fully in control and price based above the PD VAL, the reversal conditions were met. Sellers were also a bit trapped on the FP. I waited for the retest into PD VAL, saw buyers hold the level, and executed the long. Took a 1:2 targeting NY Open",
    tags: ["ORB", "Reversal", "PD VAL"],
    images: [],
    urls: []
  },
  {
    id: "t8",
    date: "2026-04-20",
    timeEntry: "10:50",
    timeClose: "10:52",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB B&R (Continuation) Model",
    entryWindow: "15m",
    entry: 26716.25,
    sl: 26754.25,
    tp: 26620,
    exit: 26620,
    pnl: 385,
    rr: 2.53,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Proper position sizing", "Traded in kill zone"],
    mentalPre: "Disciplined",
    mentalDuring: "Focused",
    mentalPost: "Satisfied",
    notes: "",
    tags: ["ORB", "Continuation"],
    images: [],
    urls: []
  },
  {
    id: "t9",
    date: "2026-04-20",
    timeEntry: "09:53",
    timeClose: "09:57",
    symbol: "NQ",
    direction: "Long",
    session: "New York",
    strategy: "15m ORB Reversal Model",
    entryWindow: "5m",
    entry: 26754.5,
    sl: 26729.25,
    tp: 26805.25,
    exit: 26805.25,
    pnl: 203,
    rr: 2.01,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Traded in kill zone"],
    mentalPre: "Distracted",
    mentalDuring: "Focused",
    mentalPost: "Balanced",
    notes: "Was initially looking for a B&R, but once it became clear buyers were fully in control and price based above the PD VAL, the reversal conditions were met. I waited for the retest into PD VAL, saw buyers hold the level, and executed the long. Took a 1:2 targeting NY Open, which aligned with the intraday flow and the shift in control.",
    tags: ["ORB", "Reversal", "Flow"],
    images: [],
    urls: []
  },
  {
    id: "t10",
    date: "2026-04-22",
    timeEntry: "",
    timeClose: "",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB Reversal Model",
    entryWindow: "15m",
    entry: 26838,
    sl: 26880,
    tp: 26754,
    exit: 26853,
    pnl: -60,
    rr: -0.36,
    lots: 2,
    account: "Paper",
    followedRules: ["Respected stop loss", "Proper position sizing"],
    mentalPre: "Patient",
    mentalDuring: "Calm",
    mentalPost: "Balanced",
    notes: "Model setup was on ES, but I executed it on NQ since it was the weaker asset. Entry was late, so I couldn’t capture the full move — setup was solid, entry execution wasn’t. Mental state was okay, not perfect, but I stayed disciplined: once we failed to respect the IB mid, I knew the probability shifted higher, so I cut the loss in half.",
    tags: ["Small Loss", "Disciplined"],
    images: [],
    urls: []
  },
  {
    id: "t11",
    date: "2026-04-23",
    timeEntry: "09:56",
    timeClose: "10:01",
    symbol: "NQ",
    direction: "Short",
    session: "New York",
    strategy: "15m ORB Reversal Model",
    entryWindow: "5m",
    entry: 27050,
    sl: 27081,
    tp: 26989,
    exit: 26989,
    pnl: 244,
    rr: 1.97,
    lots: 2,
    account: "Paper",
    followedRules: ["Waited for confirmation", "Respected stop loss", "Proper position sizing", "Traded in kill zone"],
    mentalPre: "Distracted",
    mentalDuring: "Focused",
    mentalPost: "Balanced",
    notes: "Even in a bullish environment, volatility is high enough to produce clean reversal setups, so the focus has to stay on precision and disciplined entries. Textbook reversal setup: we took London High, failed to find follow‑through abive PD VAH, and then reversed the Opening Range. Buyers were clearly trapped at the top, and once ORB flipped, strong selling pressure confirmed the shift in control...",
    tags: ["ORB", "Reversal", "Trapped Buyers"],
    images: [],
    urls: []
  }
];
